baseURL = "http://www.apachecon.com/acasia2021"
title = "ApacheCon Asia 2021"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true

languageCode = "en-us"
DefaultContentLanguage = "en"

[languages.en]
languageName = "English"
weight = 1

[languages.zh]
languageName = "中文"
weight = 2

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

# menu for en ((final list includes translated pages from /content)
[[languages.en.menu.main]]
name = "t-shirt"
url = "https://s.apache.org/apache-tshirt"
weight = -110

[[languages.en.menu.main]]
name = "Location"
url = "/getting-started/"
weight = -100

[[languages.en.menu.main]]
name = "Schedule"
url = "tracks.html"
weight = -100

[[languages.en.menu.main]]
name = "中文"
url = "zh/"
weight = 200

# menu for ZH language (final list includes translated pages from /content)
[[languages.zh.menu.main]]
name = "马球"
url = "https://s.apache.org/apach-tshirt"
weight = -110

[[languages.zh.menu.main]]
name = "地点"
url = "/getting-started/"
weight = -100

[[languages.zh.menu.main]]
name = "日程"
url = "/tracks.html"
weight = -100

[[languages.zh.menu.main]]
name = "English"
url = "/"
weight = 200
