baseURL = "http://www.apachecon.com/acasia2021"
languageCode = "en-us"
title = "ApacheCon Asia 2021"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true

languageCode: "en-us"
DefaultContentLanguage: "en"
languages:
  en:
    languageName: English
    weight: 1
  zh:
    languageName: 中文
    weight: 2
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
